language: php

php:
    - 7.1

env:
  global:
    - "FTP_USER=serbanblebea"
    - "FTP_PASSWORD=highprotein07"

before_install:

before_script:
  - "composer install"

script:
  - "composer phpunit"

after_success:
  # - "composer install"
  - "cd deploy-node"
  - "npm install"
  - "node index.js"

branches:
  only:
    - master