language: php

php:
    - 7.1

env:
  global:
    - "FTP_USER=serbanblebea"
    - "FTP_PASSWORD=highprotein07"

before_script:
  - "composer install"

script:
  - "composer phpunit"

after_success:
  - "cd deploy-node"
  - "npm install"
  - "node index.js"
  - "ssh pi@192.168.1.23"
  - "cd /var/www/html/deploy"
  - "composer install"

branches:
  only:
    - master