language: php

php:
    - 7.1

env:
  global:
    - "FTP_USER=serbanblebea"
    - "FTP_PASSWORD=highprotein07"

before_install:

before_script:
  - "composer install"

script:
  - "composer phpunit"

after_success:
  - "curl -u serbanblebea:highprotein07 ftp://192.168.1.23/html/upload"

branches:
  only:
    - master