language: php

php:
    - 7.1

env:
  global:
    - "FTP_USER=serbanblebea"
    - "FTP_PASSWORD=highprotein07"

before_install:

before_script:
  - "composer install"

script:
  - "composer phpunit"

after_success:
  - "curl -T index.php -u $FTP_USER:$FTP_PASSWORD ftp://90.240.235.222/html/deploy/index.php"

branches:
  only:
    - master