language: php

php:
    - 7.1

env:
  global:
    - "FTP_USER=serbanblebea"
    - "FTP_PASSWORD=highprotein07"

before_install:

before_script:
  - "composer install"

script:
  - "composer phpunit"

after_success:
  - "curl --ftp-create-dirs -T deploy-folder -u $FTP_USER:$FTP_PASSWORD ftp://192.168.1.23/upload"